name: pages build and deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://stafot.dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # full SHA for v4.2.2

      - name: Install dependencies
        run: npm install

      - name: Build production bundle
        run: npm run build

      - name: Prepare output directory
        run: |
          mkdir out
          cp -r docs/* out/

      - name: Inject CNAME & disable Jekyll
        run: |
          echo "stafot.dev" > out/CNAME
          touch out/.nojekyll

      - name: Configure GitHub Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b  # full SHA for v4.0.0

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa  # full SHA for v3.0.1
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # full SHA for v4.0.5
